#!/usr/bin/env bash

# bash completion for Play Version Manager (PVM)

__pvm_generate_completion()
{
  declare current_word
  current_word="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "$1" -- "$current_word"))
  return 0
}

__pvm_commands ()
{
  declare current_word
  declare command

  current_word="${COMP_WORDS[COMP_CWORD]}"

  COMMANDS='\
    help install uninstall use\
    run ls list deactivate alias\
    unalias copy-packages clear-cache version'

    if [ ${#COMP_WORDS[@]} == 4 ]; then

      command="${COMP_WORDS[COMP_CWORD-2]}"
      case "${command}" in
      alias)  __pvm_installed_nodes ;;
      esac

    else

      case "${current_word}" in
      -*)     __pvm_options ;;
      *)      __pvm_generate_completion "$COMMANDS" ;;
      esac

    fi
}

__pvm_options ()
{
  OPTIONS=''
  __pvm_generate_completion "$OPTIONS"
}

__pvm_installed_nodes ()
{
  __pvm_generate_completion "$(pvm_ls) $(__pvm_aliases)"
}

__pvm_aliases ()
{
  declare aliases
  aliases=""
  if [ -d $PVM_DIR/alias ]; then
    aliases="`cd $PVM_DIR/alias && ls`"
  fi
  echo "${aliases}"
}

__pvm_alias ()
{
  __pvm_generate_completion "$(__pvm_aliases)"
}

__pvm ()
{
  declare previous_word
  previous_word="${COMP_WORDS[COMP_CWORD-1]}"

  case "$previous_word" in
  use|run|ls|list|uninstall) __pvm_installed_nodes ;;
  alias|unalias)  __pvm_alias ;;
  *)              __pvm_commands ;;
  esac

  return 0
}

# complete is a bash builtin, but recent versions of ZSH come with a function 
# called bashcompinit that will create a complete in ZSH. If the user is in 
# ZSH, load and run bashcompinit before calling the complete function.
if [[ -n ${ZSH_VERSION-} ]]; then
	autoload -U +X bashcompinit && bashcompinit
fi

complete -o default -o nospace -F __pvm pvm

